### ISSUE TITLE
typo in docs https://dash-julia.plotly.com/basic-callbacks 

### ISSUE THREAD

**Issue by waralex** [plotly/dash-julia-docs#30]
I'm just transferring the issue https://github.com/plotly/Dash.jl/issues/122 from @mzaffalon here.
Original text:
>I would like to report a typo in the the example in the section Dash App With Multiple Inputs.
xaxis_type = xaxis_type == "Linear" ? "linear" : "log", should read xaxis_type = xaxis_type == "linear" ? "linear" : "log", and similarly for the xaxis_type.

**Comment by sglyon** [comment]
Closed in #20 !
